name: Hourly Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  hourly-job:
    uses: paulopiriquito/cron-releases/.github/workflows/get-latest-release-tag.yaml@master
    with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
  checkout-release:
    runs-on: ubuntu-latest
    needs: [hourly-job]
    if: needs.hourly-job.outputs.found == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.hourly-job.outputs.tag }}
