name: Hourly Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  hourly-job:
    uses: paulopiriquito/cron-releases/.github/workflows/get-latest-release-tag.yaml@master
    with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
