name: Hourly Workflow

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/5 * * * *'

jobs:
  find-scheduled-release:
    uses: paulopiriquito/cron-releases/.github/workflows/get-latest-release-tag.yaml@master
    with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
  set-git-ref:
    runs-on: ubuntu-latest
    needs:
      - find-scheduled-release
    outputs:
      use-ref: ${{ steps.find-git-ref.outputs.git-ref }}
    steps:
      - name: Set current ref if not scheduled
        id: find-git-ref
        run: |
          if test "${{ github.event_name }}" = "schedule" && test "${{ needs.find-scheduled-release.outputs.found }}" = "true"; then
            echo -n "git-ref=refs/tags/${{ needs.find-scheduled-release.outputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo -n "git-ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          fi
  checkout-release:
    runs-on: ubuntu-latest
    needs:
      - set-git-ref
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.set-git-ref.outputs.use-ref }}
